#!/bin/bash

set -e
set -u
#set -o pipefail

echo "" >.env
_usage(){
  APP=$(basename "$0")
      echo
      echo "Usage: $APP [options] <action[start|stop|build> <enviorment[addons|test|prod|dev>"

      echo "    Special options:"
      echo
      echo "      -i           load an specific image"
      echo "      -a           load local linkaform_api as volume"
      echo "      -r           relaod, alway need to be at the end of the options"
      echo "      -c           works on build command, it runs the build command with no-cache"
      echo "      -h           help!!!!"
      echo
      echo "    Acction & Enviorment"
      echo "      $APP <start|stop> addons     Starts the addons development environment"
      echo "      $APP <start|stop> test       Starts the testing environment"
      echo "      $APP build <prod|dev>      Starts the testing environment"
      echo
      echo
      exit 1
}


API_VOL=0
IMAGE_NAME=0
SHIFT=-1
NOCACHE=0
while getopts ':iar:ir:c:h' opt; do
  case "$opt" in
    a)
      echo "Loding local API..."
      if [ "$IMAGE_NAME" != "0" ]; then
        SHIFT=0
      else
        SHIFT=-1
      fi
      API_VOL=1
      ;;
    i)
      echo "Setting image..."
      SHIFT=-0
      IMAGE_NAME=$2
      ;;
    c)
      echo "No-Cache build"
      NOCACHE= 1
      ;;
    r)
      echo "Relaoding..."
      SHIFT=-1
      if [ "$IMAGE_NAME" != "0" ]; then
        CONTAINER_NAME=$3
      else  
        CONTAINER_NAME=$2
        SHIFT=-2
      fi
      if [[ $CONTAINER_NAME == 'test' ]]; then
        docker stop lkf_test && docker rm lkf_test
      else
        docker stop lkf-addons && docker rm lkf-addons
      fi
      ;;
    h)
     #help
      echo "helpppp"
      _usage
      ;;
    ?)
      _usage
      ;;
  esac
done

echo "SHIFT" $SHIFT

if [ "$IMAGE_NAME" != "0" ]; then
  if [[ $# -ge 2 ]]; then
    shift "$(($OPTIND $SHIFT))"
  fi
else
  echo "no image ", $IMAGE_NAME
  if [ $# -ge 2 ]; then
    shift "$(($OPTIND $SHIFT))"
  fi
  IMAGE_NAME="linkaform/addons:develop"
fi
echo "IMAGE_NAME" $IMAGE_NAME


_run_addons(){
  echo "the command for was " $1
  case $1 in
    stop)
      docker stop lkf-addons && docker rm lkf-addons
    ;;
    start)
      containerID=$(docker ps | grep lkf-addons | awk '{print $1}')
      echo "container ID" $containerID
      if [ -z "$containerID" ]; then
        echo "creating new container"
        docker stop lkf-addons && docker rm lkf-addons
        if [[ $2 == 0 ]] ; then
          echo 'arranca'
          cd docker
          docker compose up -d lkf-addons && \
          # docker run   -w /srv/addons/ \
          #   -v `pwd`:/srv/addons \
          #   -v ~/lkf/custom/:/srv/custom \
          #   -v ~/.bash_history:/root/.bash_history \
          #   --name addons \
          #   -d  $IMAGE_NAME sleep infinity \
          docker exec -it lkf-addons bash
        else
          echo "Loading local addons"
          cd docker
          docker compose up -d lkf-addons && \
          # docker run   -w /srv/addons/ \
          #   -v `pwd`:/srv/addons \
          #   -v ~/lkf/custom/:/srv/custom \
          #   -v ~/lkf/linkaform_api/linkaform_api:/usr/local/lib/python3.7/site-packages/linkaform_api/  \
          #   -v ~/.bash_history:/root/.bash_history \
          #   --name addons \
            # -d $IMAGE_NAME sleep infinity \
            docker exec -it lkf-addons bash
        fi
      else
        echo "Joinign existing"
        docker exec -it $containerID bash ;
      fi
     ;;
  esac

}

_start_addons(){
  echo "the command for was " $1
  echo "the command for was 2" $2
  case $1 in
    test)
      docker stop lkf-addons && docker rm lkf-addons
    ;;
    addons)
      containerID=$(docker ps | grep lkf-addons | awk '{print $1}')
      echo "container ID" $containerID
      if [ -z "$containerID" ]; then
        echo "creating new container"
        docker stop lkf-addons && docker rm lkf-addons
        if [[ $2 == 0 ]] ; then
          echo 'arranca'
          cd docker
          docker compose up -d lkf-addons && \
          # docker run   -w /srv/addons/ \
          #   -v `pwd`:/srv/addons \
          #   -v ~/lkf/custom/:/srv/custom \
          #   -v ~/.bash_history:/root/.bash_history \
          #   --name addons \
          #   -d  $IMAGE_NAME sleep infinity \
          docker exec -it lkf-addons bash
        else
          echo "Loading local addons"
          cd docker
          docker compose up -d lkf-addons && \
          # docker run   -w /srv/addons/ \
          #   -v `pwd`:/srv/addons \
          #   -v ~/lkf/custom/:/srv/custom \
          #   -v ~/lkf/linkaform_api/linkaform_api:/usr/local/lib/python3.7/site-packages/linkaform_api/  \
          #   -v ~/.bash_history:/root/.bash_history \
          #   --name addons \
            # -d $IMAGE_NAME sleep infinity \
            docker exec -it lkf-addons bash
        fi
      else
        echo "Joinign existing"
        docker exec -it $containerID bash ;
      fi
     ;;
  esac

}

_build(){
  echo "Environment: " $1
  cd docker
  case $1 in
    dev)
      if [ "$NOCACHE" != "0" ]; then
        docker compose build lkf-addons
      else
        docker compose build --no-cache lkf-addons
      fi
      docker push linkaform/addons:develop
    ;;
    prod)
      if [ "$NOCACHE" != "0" ]; then
        docker compose -f docker-prod.yml build
      else
        docker compose -f docker-prod.yml build --no-cache
      fi
      docker push linkaform/addons:latest
     ;;
  esac
  cd ..

}

_udpate_container(){
  #TODO, actualizar contenedor de addons corriendo en ambiente de pruebas
  #docker cp stock_utils.py account_9908_linkaform.addons..latest:/usr/local/lib/python3.7/site-packages/lkf_addons/addons/stock/stock_utils.py
  echo "TODO"
}

_run_tests(){
  echo "the command for was " $1
  case $1 in
    stop)
      docker stop lkf_test && docker rm lkf_test
    ;;
    start)
      cd ~/lkf/addons/test/docker
      containerID=$(docker ps | grep lkf_test | awk '{print $1}')
      echo "container ID" $containerID
      if [ -z "$containerID" ]; then
        echo "creating new container"
        docker stop lkf_test && docker rm lkf_test
        docker compose up -d
        docker exec -it lkf_test bash
      else
        echo "Joinign existing"
        docker exec -it $containerID bash ;
      fi
     ;;
  esac

}


Acction=""
if [[ $# -gt 0 ]]; then
  Acction=$1

fi

echo "Acction : $Acction"
#echo $Acction >>.env

Service=0
if [[ $# -gt 1 ]]; then
  Service=$2
fi

Branch=""
if [[ $# -gt 2 ]]; then
  Branch=$3
fi




case "$Acction" in


  addons)
    echo "Addons > > > >" $API_VOL
    _run_addons $Service $API_VOL
  ;;
  start)
    echo "Addons" $API_VOL
    _start_addons $Service $API_VOL
  ;;
  build)
    echo "building addons image" 
    _build $Service
  ;;

  test)
    echo "Loding testing environment . . . . + - / * "
    _run_tests $Service
  ;;
  ?)
   _usage
   ;;
esac
