volumes:
  infosync_media:


networks:
  linkaform:
    name: linkaform
    external: true

services:
  lkf-addons:
    restart: "no"
    container_name: lkf-addons
    image: linkaform/addons:latest
    build:    
     context: ../
     dockerfile: ./Dockerfile
     target: prod
    stdin_open: true
    tty: true
